export enum Designation {
  HOD = "HOD",

  PROFESSOR = "PROFESSOR",

  ASSOCIATE_PROFESSOR = "ASSOCIATE_PROFESSOR",

  ASSISTANT_PROFESSOR = "ASSISTANT_PROFESSOR",

  LECTURER = "LECTURER",

  VISITING_FACULTY = "VISITING_FACULTY",
}