export enum NotificationType {
  ANNOUNCEMENT = "ANNOUNCEMENT",

  ASSIGNMENT = "ASSIGNMENT",

  EXAMINATION = "EXAMINATION",

  RESULT = "RESULT",

  ATTENDANCE = "ATTENDANCE",

  SYSTEM = "SYSTEM",
}